### ISSUE TITLE
System Wide - Related Records Functionality on R4C 

### ISSUE THREAD

**Issue by JuanitaMiles** [JuanitaMiles/FredCo_Future_Phases#61]
**Source:**
Repository: dhenry-KCI/FredCo-Post-Go-Live-
Ticket #: 305
Requested By: Ashlye Bonomo
[Jump to this repository](https://github.com/dhenry-KCI/FredCo-Post-Go-Live-/issues/305)

**Request:**
Need to restrict applicants from editing the related records that are displayed in R4C. They are currently able to add and delete permits which can cause problems. For now, related records have been turned off on the portal.

**Comment by ABonomo21** [comment]
Received an Email from Mark Oliver 2.10.20- There is a fix for the related records issue coming in the May release for R4C. 
Email content from Mark - 
Hi Ashlye,
 
Thank you again for taking the time last week to discuss your needs regarding the add/delete option for related records.
 
We understand and appreciate the impact on your business. I have spoken with Daniel West, the development manager for Civics, and we have rearranged the roadmap in order to provide the needed functionality in our May release.
 
Let me know if you have any further questions.

**Comment by ABonomo21** [comment]
Related to Project Tickets from Post Golive list 383 and Note regarding Mobile

**Comment by ABonomo21** [comment]
Related to ticket #34

**Comment by JuanitaMiles** [comment]
Release notes indicate updated functionality has been added to R4C in the 20.05 release. This new functionality should become available when we upgrade IPS back office to 11.2 202007. (This will include everything in 20.05 as well)

![image](https://user-images.githubusercontent.com/31770504/86821146-01ea2a80-c058-11ea-87c8-32a58eb63b05.png)
![image](https://user-images.githubusercontent.com/31770504/86821197-129aa080-c058-11ea-8726-b28f5787e03d.png)

**Comment by JuanitaMiles** [comment]
Functionality will be activated when we complete the "07" patch update.

**Comment by JuanitaMiles** [comment]
Migrated to Sprint 2 to be confirmed with the "07" update. See ticket [28](https://github.com/JuanitaMiles/FredCo_Phase2_FY21/issues/28)
